/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author vinay
 */
public class adminp1 extends javax.swing.JPanel {

    /**
     * Creates new form adminp1
     */
    public adminp1() {
        initComponents();
        fillcombo();
    }
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    ResultSet rs2=null;
    ResultSet rs3=null;
    ResultSet rs4=null;
    ResultSet rs5=null;
    ResultSet rs6=null;
    String genderr2;
    private void fillcombo()
    {
        conn=mysqlconnect.ConnectDB();  
        try
        {      
        String abc="select * from clerk";
        pst=conn.prepareStatement(abc);
        rs=pst.executeQuery();
        
        while(rs.next())
        {
            String n1=rs.getString("c_id");
            jComboBox1.addItem(n1);
        }
        }
        catch(Exception e)
        {   
        JOptionPane.showMessageDialog(null,e);
        }
    }
    private void update_table()
    {
        conn=mysqlconnect.ConnectDB();
        String sql6="select * from employee";
        //String sql7="select * from payroll";
        try 
        {            
        pst=conn.prepareStatement(sql6);
        rs3=pst.executeQuery();
        jTable3.setModel(DbUtils.resultSetToTableModel(rs3));
             
        } catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null,ex);
        }                        
    }
       private void update_table2()
    {
       // String sql6="select * from employee";
        String sql7="select * from payroll";
        try 
        {            
        pst=conn.prepareStatement(sql7);
        rs4=pst.executeQuery();
        jTable4.setModel(DbUtils.resultSetToTableModel(rs4));
             
        } catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null,ex);
        }                        
    }
        private void update_table3()
    {
       // String sql6="select * from employee";
        String sql9="select * from projects";
        try 
        {            
        pst=conn.prepareStatement(sql9);
        rs6=pst.executeQuery();
        jTable2.setModel(DbUtils.resultSetToTableModel(rs6));
             
        } catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null,ex);
        }                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        getlist = new javax.swing.JButton();
        seeprojects = new javax.swing.JButton();
        manageclerk = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        createprojects = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        deletepro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        designation1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        femaleradio1 = new javax.swing.JRadioButton();
        jTextField14 = new javax.swing.JTextField();
        updatetable = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        ename1 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        maleradio1 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        deletetable = new javax.swing.JButton();
        eid1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        contactno1 = new javax.swing.JTextField();
        department1 = new javax.swing.JTextField();
        refreshemployee = new javax.swing.JButton();
        refreshpayroll = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addclerk = new javax.swing.JButton();
        updateclerk = new javax.swing.JButton();
        deleteclerk = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        getlist.setText("EDIT/GET EMPLOYEE LIST");
        getlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getlistActionPerformed(evt);
            }
        });

        seeprojects.setText("CREATE/ASSIGN PROJECTS");
        seeprojects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeprojectsActionPerformed(evt);
            }
        });

        manageclerk.setText("MANAGE CLERKS");
        manageclerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageclerkActionPerformed(evt);
            }
        });

        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(manageclerk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seeprojects, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getlist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(getlist, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(seeprojects, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(manageclerk, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel12.setText("WELCOME TO EMPLOYEE MANAGEMENT AND PAYROLL SERVICES");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel12)
                .addContainerGap(942, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, "card4");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("CREATE PROJECT"));

        jLabel2.setText("PROJECT NAME:");

        jLabel4.setText("AVIALABILITY:");

        jLabel3.setText("ELIGIBILITY:");

        jLabel1.setText("PROJECT ID:");

        createprojects.setFont(new java.awt.Font("Lucida Fax", 1, 11)); // NOI18N
        createprojects.setText("CREATE");
        createprojects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createprojectsActionPerformed(evt);
            }
        });
        createprojects.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                createprojectsKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Fax", 1, 11)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        deletepro.setFont(new java.awt.Font("Lucida Fax", 1, 11)); // NOI18N
        deletepro.setText("DELETE");
        deletepro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteproActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createprojects)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(deletepro)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createprojects)
                    .addComponent(jButton1)
                    .addComponent(deletepro))
                .addGap(20, 20, 20))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText(" PROJECT LIST:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(982, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(376, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, "card3");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("EMPLOYEE INFO"));

        jLabel28.setText("HIRE DATE:");

        jLabel26.setText("DESIGNATION:");

        jLabel24.setText("DOB:");

        jLabel27.setText("DEPARTMENT:");

        femaleradio1.setText("female");
        femaleradio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleradio1ActionPerformed(evt);
            }
        });

        updatetable.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        updatetable.setText("UPDATE INFO");
        updatetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatetableActionPerformed(evt);
            }
        });

        jLabel23.setText("GENDER:");

        maleradio1.setText("male");
        maleradio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleradio1ActionPerformed(evt);
            }
        });

        jLabel22.setText("EMPLOYEE_ID:");

        deletetable.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        deletetable.setText("DELETE EMPLOYEE");
        deletetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletetableActionPerformed(evt);
            }
        });

        jLabel25.setText("CONTACT_NO:");

        jLabel21.setText("EMPLOYEE_NAME:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(maleradio1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(femaleradio1))
                            .addComponent(eid1)
                            .addComponent(ename1)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(updatetable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contactno1)
                            .addComponent(designation1)
                            .addComponent(department1)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(deletetable)))
                .addGap(22, 22, 22))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(ename1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(eid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleradio1)
                            .addComponent(femaleradio1)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel27)
                                .addComponent(department1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel28)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(contactno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(designation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatetable, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletetable, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        refreshemployee.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        refreshemployee.setText("REFRESH EMPLOYEE TABLE");
        refreshemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshemployeeActionPerformed(evt);
            }
        });

        refreshpayroll.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        refreshpayroll.setText("REFRESH PAYROLL TABLE");
        refreshpayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshpayrollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addGap(32, 32, 32)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(refreshemployee))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(refreshpayroll)))
                .addContainerGap(863, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(refreshemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshpayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, "card2");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("CLERK DETAILS"));

        jLabel7.setText("CLERK ID:");

        jLabel9.setText("PASSWORD:");

        jLabel10.setText("CONTACT NO:");

        jLabel8.setText("USERID:");

        jLabel6.setText("CLERK NAME:");

        addclerk.setFont(new java.awt.Font("Lucida Fax", 1, 11)); // NOI18N
        addclerk.setText("ADD");
        addclerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addclerkActionPerformed(evt);
            }
        });

        updateclerk.setFont(new java.awt.Font("Lucida Fax", 1, 11)); // NOI18N
        updateclerk.setText("UPDATE");
        updateclerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateclerkActionPerformed(evt);
            }
        });

        deleteclerk.setFont(new java.awt.Font("Lucida Fax", 1, 11)); // NOI18N
        deleteclerk.setText("DELETE");
        deleteclerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteclerkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(65, 65, 65))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(addclerk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(updateclerk)
                .addGap(33, 33, 33)
                .addComponent(deleteclerk)
                .addGap(23, 23, 23))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addclerk)
                    .addComponent(deleteclerk)
                    .addComponent(updateclerk))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("GET CLERK LIST:");

        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1126, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getlistActionPerformed
       jPanel2.removeAll();
       jPanel2.repaint();
       jPanel2.revalidate();
       //adding panels
       jPanel2.add(jPanel3);
       jPanel2.repaint();
       jPanel2.revalidate();
       update_table();
       update_table2();
    }//GEN-LAST:event_getlistActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked

        try
        {
            int row=jTable3.getSelectedRow();
            String table_click=(jTable3.getModel().getValueAt(row, 1).toString());
            String sql9="select * from employee where emp_id ='"+table_click+"'";
            pst=conn.prepareStatement(sql9);
            rs5=pst.executeQuery();

            while(rs5.next())
            {
                String s1=rs5.getString("name");
                String s2=rs5.getString("emp_id");
                String s3=rs5.getString("gender");
                String s4=rs5.getDate("dob").toString();
                String s8=rs5.getString("contact_no");
                String s5=rs5.getString("designation");
                String s6=rs5.getString("department");
                String s7=rs5.getDate("hire_date").toString();

                ename1.setText(s1);
                eid1.setText(s2);
                if("male".equals(s3))
                {
                    maleradio1.setSelected(true);
                    femaleradio1.setSelected(false);
                }
                else
                {
                    maleradio1.setSelected(false);
                    femaleradio1.setSelected(true);
                }
                jTextField13.setText(s4);
                contactno1.setText(s8);
                designation1.setText(s5);
                department1.setText(s6);
                jTextField14.setText(s7);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void femaleradio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleradio1ActionPerformed
        if(femaleradio1.isSelected())
        genderr2="female";
    }//GEN-LAST:event_femaleradio1ActionPerformed

    private void updatetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatetableActionPerformed

        try
        {
            String value1=ename1.getText();
            String value2=eid1.getText();
            String value3=genderr2;
            String value4=jTextField13.getText();
            String value5=contactno1.getText();
            String value6=designation1.getText();
            String value7=department1.getText();
            String value8=jTextField14.getText();

            String sql7="update employee set name='"+value1+"',emp_id='"+value2+"',gender='"+value3+"',dob='"+value4+"',contact_no='"+value5+"',designation='"+value6+"',department='"+value7+"',hire_date='"+value8+"' where emp_id='"+value2+"'";
            pst=conn.prepareStatement(sql7);
            pst.execute();
            JOptionPane.showMessageDialog(null,"UPDATED SUCCESSFULLY");
        }
        catch(SQLException | HeadlessException e4)
        {
            JOptionPane.showMessageDialog(null,e4);
        }
    }//GEN-LAST:event_updatetableActionPerformed

    private void maleradio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleradio1ActionPerformed
        if(maleradio1.isSelected())
        genderr2="male";
    }//GEN-LAST:event_maleradio1ActionPerformed

    private void deletetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletetableActionPerformed
        try
        {
            String sql8="delete from employee where emp_id=?";
            pst=conn.prepareStatement(sql8);
            pst.setString(1,eid1.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"DELETED SUCCESSFULLY");
        }
        catch(SQLException | HeadlessException e3)
        {
            JOptionPane.showMessageDialog(null,e3);
        }
    }//GEN-LAST:event_deletetableActionPerformed

    private void refreshemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshemployeeActionPerformed
        update_table();
    }//GEN-LAST:event_refreshemployeeActionPerformed

    private void refreshpayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshpayrollActionPerformed
        update_table2();
    }//GEN-LAST:event_refreshpayrollActionPerformed

    private void createprojectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createprojectsActionPerformed
        //conn=mysqlconnect.ConnectDB();
        try
        {
            String sql9="insert into projects (project_id,p_name,eligibility,availability) values(?,?,?,?)";
            pst=conn.prepareStatement(sql9);
            pst.setString(1,jTextField1.getText());
            pst.setString(2,jTextField2.getText());
            pst.setString(3,jTextField3.getText());
            pst.setString(4,jTextField4.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"PROJECT CREATED SUCCESSFULLY");
        }
        catch(SQLException | HeadlessException e3)
        {
            JOptionPane.showMessageDialog(null,e3);
        }
    }//GEN-LAST:event_createprojectsActionPerformed

    private void createprojectsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createprojectsKeyPressed
        //conn=mysqlconnect.ConnectDB();
        try
        {
            String sql9="insert into projects (project_id,p_name,eligibility,availability) values(?,?,?,?)";
            pst=conn.prepareStatement(sql9);
            pst.setString(1,jTextField1.getText());
            pst.setString(2,jTextField2.getText());
            pst.setString(3,jTextField3.getText());
            pst.setString(4,jTextField4.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"PROJECT CREATED SUCCESSFULLY");
        }
        catch(SQLException | HeadlessException e3)
        {
            JOptionPane.showMessageDialog(null,e3);
        }
    }//GEN-LAST:event_createprojectsKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try
        {
            String value1=jTextField1.getText();
            String value2=jTextField2.getText();            
            String value4=jTextField3.getText();
            String value5=jTextField4.getText();            
            String sql11="update projects set p_name='"+value2+"',eligibility='"+value4+"',availability='"+value5+"' where project_id='"+value1+"'";
            pst=conn.prepareStatement(sql11);
            pst.execute();
            JOptionPane.showMessageDialog(null,"UPDATED SUCCESSFULLY");
        }
        catch(SQLException | HeadlessException e4)
        {
            JOptionPane.showMessageDialog(null,e4);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteproActionPerformed
        
        try
        {
            String sql3="delete from projects where project_id=?";
            pst=conn.prepareStatement(sql3);  
            pst.setString(1,jTextField1.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"DELETED SUCCESSFULLY");
        }
        catch(SQLException | HeadlessException e3)
        {
            JOptionPane.showMessageDialog(null,e3);
        }            
    }//GEN-LAST:event_deleteproActionPerformed

    private void seeprojectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeprojectsActionPerformed
       jPanel2.removeAll();
       jPanel2.repaint();
       jPanel2.revalidate();
       //adding panels
       jPanel2.add(jPanel4);
       jPanel2.repaint();
       jPanel2.revalidate();
        update_table3();
    }//GEN-LAST:event_seeprojectsActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        try
        {
            int row=jTable2.getSelectedRow();
            String table_click=(jTable2.getModel().getValueAt(row, 0).toString());
            String sql10="select * from projects where project_id ='"+table_click+"'";
            pst=conn.prepareStatement(sql10);
            rs5=pst.executeQuery();

            while(rs5.next())
            {
                String s1=rs5.getString("project_id");
                String s2=rs5.getString("p_name");                                
                String s8=rs5.getString("eligibility");
                String s5=rs5.getString("availability");               

                jTextField1.setText(s1);
                jTextField2.setText(s2);                          
                jTextField3.setText(s8);
                jTextField4.setText(s5);
              
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void manageclerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageclerkActionPerformed
       jPanel2.removeAll();
       jPanel2.repaint();
       jPanel2.revalidate();
       //adding panels
       jPanel2.add(jPanel7);
       jPanel2.repaint();
       jPanel2.revalidate();
    }//GEN-LAST:event_manageclerkActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.removeAll();
        this.repaint();
        this.revalidate();
        home n1=new home();
        n1.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void updateclerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateclerkActionPerformed
         try
        {
            String value1=jTextField5.getText();
            String value2=jTextField6.getText();            
            String value4=jTextField7.getText();
            String value5=jTextField8.getText();
            String value6=jTextField9.getText();            
            
            String sql2="update clerk set clerk_name='"+value1+"',c_id='"+value2+"',username='"+value4+"',password='"+value5+"',contact_no='"+value6+"' where c_id='"+value2+"'";
            pst=conn.prepareStatement(sql2);
            pst.execute();
            JOptionPane.showMessageDialog(null,"UPDATED SUCCESSFULLY");
        }
        catch(SQLException | HeadlessException e4)
        {
            JOptionPane.showMessageDialog(null,e4);
        }
    }//GEN-LAST:event_updateclerkActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        String temp=(String)jComboBox1.getSelectedItem();            
        String sql7="select * from clerk where c_id ='"+temp+"'";
        try
        {            
            pst=conn.prepareStatement(sql7);
            rs2=pst.executeQuery();
            
            
            while(rs2.next())
            {
            String s1=rs2.getString("clerk_name");
            String s2=rs2.getString("c_id");            
            String s3=rs2.getString("username");            
            String s8=rs2.getString("password");
            String s9=rs2.getString("contact_no");
            
            jTextField5.setText(s1);
            jTextField6.setText(s2);                       
            jTextField7.setText(s3);
            jTextField8.setText(s8);
            jTextField9.setText(s9);           
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void addclerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addclerkActionPerformed
         String Sql;
         Sql = "insert into clerk (clerk_name,c_id,username,password,contact_no) values(?,?,?,?,?)";
        try
        {
            pst=conn.prepareStatement(Sql);
            pst.setString(1,jTextField5.getText());
            pst.setString(2,jTextField6.getText());
            pst.setString(3,jTextField7.getText());            
            pst.setString(4,jTextField8.getText());
            pst.setString(5,jTextField9.getText());            
                                 
            pst.execute();
            JOptionPane.showMessageDialog(null,"CLERK ADDED");
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_addclerkActionPerformed

    private void deleteclerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteclerkActionPerformed
        try
        {
            String sql3="delete from clerk where c_id=?";
            pst=conn.prepareStatement(sql3);  
            pst.setString(1,jTextField6.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"DELETED SUCCESSFULLY");
        }
        catch(SQLException | HeadlessException e3)
        {
            JOptionPane.showMessageDialog(null,e3);
        }     
    }//GEN-LAST:event_deleteclerkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addclerk;
    private javax.swing.JTextField contactno1;
    private javax.swing.JButton createprojects;
    private javax.swing.JButton deleteclerk;
    private javax.swing.JButton deletepro;
    private javax.swing.JButton deletetable;
    private javax.swing.JTextField department1;
    private javax.swing.JTextField designation1;
    private javax.swing.JTextField eid1;
    private javax.swing.JTextField ename1;
    private javax.swing.JRadioButton femaleradio1;
    private javax.swing.JButton getlist;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton logout;
    private javax.swing.JRadioButton maleradio1;
    private javax.swing.JButton manageclerk;
    private javax.swing.JButton refreshemployee;
    private javax.swing.JButton refreshpayroll;
    private javax.swing.JButton seeprojects;
    private javax.swing.JButton updateclerk;
    private javax.swing.JButton updatetable;
    // End of variables declaration//GEN-END:variables
}
